### ISSUE TITLE
Literal string arrays generates wrong type

### ISSUE THREAD

**Issue by ckarli** [hosseinmd/swagger-typescript#58]
An array of literal strings like this
![image](https://github.com/hosseinmd/swagger-typescript/assets/87313837/df53f7d9-b00b-481a-8e27-f89d0e7be473)

generates a type like this
`  state?: "CANCEL" | "OUT" | "PAID" | "PORTFOLIO" | "RETURNOUT" | "UNDEFINED"[];`

but it should generate 
`  state?: ("CANCEL" | "OUT" | "PAID" | "PORTFOLIO" | "RETURNOUT" | "UNDEFINED")[];
`

**Comment by ckarli** [comment]
After last update, can't generate types at all.
[schema.json](https://github.com/user-attachments/files/21932936/schema.json)
[{
  "url": "http://127.0.0.1:8000/api/schema/?format=json",
  "dir": "./types",
  "reactHooks": true,
  
  "useInfiniteQuery": ["useGetSuppliersSuppliers","useGetWarehouseWarehouses","useGetFinanceAccounts"]
}
]


`SyntaxError: Type expected. (11481:43)
  11479 |         
  11480 |         
> 11481 |         export type PaymentBondStateEnum =;
        |                                           ^
  11482 |         
  11483 |         
  11484 |         export interface PaymentCheque {
    at S4 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:72190)
    at Q4 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:20:1042)
    at Object.e3 [as parse] (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:20:1584)
    at parse5 (file:///workspace/frontend/node_modules/prettier/index.mjs:16731:24)
    at async coreFormat (file:///workspace/frontend/node_modules/prettier/index.mjs:17287:25)
    at async formatWithCursor (file:///workspace/frontend/node_modules/prettier/index.mjs:17504:14)
    at async format2 (file:///workspace/frontend/node_modules/prettier/index.mjs:19051:25)
    at async formatFile (file:///workspace/frontend/node_modules/swagger-typescript/lib/javascript/index.mjs:87:29) {
  loc: {
    start: { line: 11481, column: 43 },
    end: { line: 11481, column: 43 }
  },
  cause: $f: Type expected.
      at ed (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:8771)
      at ad (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:10704)
      at e0 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:66963)
      at x4 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:72051)
      at h0 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:71793)
      at file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:20:1548
      at w4 (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:17:72344)
      at Object.e3 [as parse] (file:///workspace/frontend/node_modules/prettier/plugins/typescript.mjs:20:1532)
      at parse5 (file:///workspace/frontend/node_modules/prettier/index.mjs:16731:24)
      at async coreFormat (file:///workspace/frontend/node_modules/prettier/index.mjs:17287:25) {
    fileName: 'estree.ts',
    location: {
      end: { column: 42, line: 11481, offset: 198280 },
      start: { column: 42, line: 11481, offset: 198280 }
    }
  },
  codeFrame: '\x1B[0m \x1B[90m 11479 |\x1B[39m         \n' +
    ' \x1B[90m 11480 |\x1B[39m         \n' +
    '\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 11481 |\x1B[39m         \x1B[36mexport\x1B[39m type \x1B[33mPaymentBondStateEnum\x1B[39m \x1B[33m=\x1B[39m\x1B[33m;\x1B[39m\n' +
    ' \x1B[90m       |\x1B[39m                                           \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\n' +
    ' \x1B[90m 11482 |\x1B[39m         \n' +
    ' \x1B[90m 11483 |\x1B[39m         \n' +
    ' \x1B[90m 11484 |\x1B[39m         \x1B[36mexport\x1B[39m \x1B[36minterface\x1B[39m \x1B[33mPaymentCheque\x1B[39m {\x1B[0m'
}

Node.js v22.18.0
error: script "generate-types" exited with code 1`

**Comment by hosseinmd** [comment]
Please share your json file, i don't have any things to test.

**Comment by ckarli** [comment]
It is included in my post as schema.json
